forms/mean.py
from flask_wtf import FlaskForm 
from wtforms import StringField, PasswordField, FileField,IntegerField, SubmitField
from wtforms.validators import DataRequired
from flask_wtf.file import FileRequired, FileAllowed
class DirectInsc(FlaskForm):
    nom = StringField("nom",
    validators=[DataRequired()])
    mot_passe= PasswordField("mot de passe", validators=[DataRequired()])
    submit= SubmitField("s'inscrire")
class ProduitFormu(FlaskForm):
    nom = StringField('nom', validators=[DataRequired()])
    prix = IntegerField('prix', validators=[DataRequired()])
    image = FileField('image', validators=[FileRequired()]), FileAllowed(['jpg','png'])
    soumettre = SubmitField('ajouter')

app.py
from flask import Flask, render_template,request,redirect
from flask_wtf import CSRFProtect
import secrets
from flask import Blueprint
from flask import session, url_for
from routes import admin_routes
from flask_wtf import CSRFProtect
from routes.admin_routes import admin_bp
import sqlite3
import os
app =  Flask(__name__)
@app.route('/index', methods=['POST','GET'])
def identifier():
    return render_template('index.html')
app.register_blueprint(admin_bp, url_prefix='/admin')
app.config['SECRET_KEY'] = "manzo2025madissou"
activation_csrf = CSRFProtect(app)
@app.route('/afficher')
def affiche():
    nom = request.form['nom']
    prenom = request.form['prenom']
    numero = request.form['numero']
    centre_interet = request.form['centre d\'interet']
    conn = sqlite3.connect('clients.db')
    curseur = conn.cursor()
    curseur.execute("INSERT INTO clients nom, prenom,numero VALUES (nom, prenom, numero)")
    curseur.commit()
    curseur.close()
    return redirect(url_for('nous.html'))
if __name__ == '__main__':
    port = int(os.environ.get("port", 5000))
    app.run(debug=True, port=port)

routes/admin_routes.py
from flask import Flask,render_template,request,redirect,session
from flask import Blueprint,url_for
from mod import init_db, ajouter_produit, obtenir_produit
import sqlite3
from forms.mean import ProduitFormu
from forms.mean import DirectInsc
from forms.mean import ProduitFormu
from flask_bcrypt import Bcrypt
import hashlib
import sqlite3
admin_bp = Blueprint('admin_bp', __name__, url_prefix='/admin')
@admin_bp.route('/requete', methods=['POST', 'GET'])
def catalogue():
    if request.method == 'POST':
        nom = request.form['nom']
        prix = int(request.form['prix'])
        image = request.form['image']
        ajouter_produit(nom, prix, image)
    if request.method == 'POST':
        if not session.get('is_admin'):
            return "Acces refuser"
@admin_bp.route('/ajouter', methods=['POST', 'GET'])
def ajouter():
    nom = request.form.get('nom du produit')
    prix = request.form.get('prix')
    image = request.form.get('image')
    print("produit ajouter")
    return redirect(url_for('admin_bp.ajouter'))
@admin_bp.route('/verifier', methods=['POST', 'GET'])
def verifier():
    Nom = request.form.get('Nom')
    mot_de_passe = request.form.get('Mot_passe') 
    if mot_passe == 'Mot_de_passe':
        session['is_admin'] = True
    return redirect(url_for('admin_bp.verifier'))
    return "mot de passe incorrect"
@admin_bp.route('/deconn', methods=['POST'])
def logout():
    session.clear()
    return redirect(url_for('deconnecte'))
@admin_bp.route('/voire', methods=['POST'])
def traiter():
    form = DirectInsc()
    if form.validate_on_submit():
        nom = form.nom.data
        mot_de_passe = form.password.data
        hasher = Bcrypt.generate_password_hash(mot_passe).decode('utf-8')
        print("inscription reussie avec succes")
    return render_template('publ.html')
@admin_bp.route('/validation', methods=['POST','GET'])
def publier():
    prod = ProduitFormu()
    if prod.validate_on_submit():
        nom = prod.nom.data
        prix = prod.prix.data
        image = prod.image.data
        print("publication reussie")    
        conn = sqlite3.connect('produits.db')
        cursor = conn.cursor()
        cursor.execute('''
        CREATE TABLE IF NOT EXISTS produits (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        nom TEXT NOT NULL,
        prix INT NOT NULL,
        image file NOT NULL
        )
        ''')
        cursor.execute("INSERT INTO produits (nom,prix,image)VALUES(?,?,?)",(nom,prix,image))
        conn.commit()
        conn.close()
    return render_template('publ.html',prod=prod)

routes/utili_routes.py
from flask import Blueprint,render_template
from mod import obtenir_produits
utiliser = Blueprint('user', __name__)
@utiliser_bp.route('/utilisera')
def catalogue():
    produits = obtenir_produits()
    return render_template('catalogue.html',
    produits=produits)

templates/accueil.html
<!Doctype html>
<html>
 <head>
 <title>accueillir</title>
 </head>
<body>
 <form>
 <input type="text" name="recherche" placeholder="rechercher un produit" required><br>
 </form>
</body>
 </html>

templates/adm_pub.html
<!Doctype html>
<html lang="fr">
<head>
   <meta charset="utf-8">
   <title>formulaire d'inscription</title>
   <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
</head>
<body>
  <h1> interface admin </h1>
    <form method="POST" action="{{ url_for('admin_bp.publier')}}">
	   {{ form.csrf_token() }}
	   {{ form.mot_passe() }}
	    <input type="text" name="nom" placeholder="Nom" required> <br>
		<input type="password" name="mot_passe" placeholder="Mot de passe" required> <span class="toggle-password" onclick="togglePassword()"C:\Users\DELL\Documents\efb12400ad7394cf9c64054792af4d8d.jpg"></span><br>
		<button type="submit">s'inscrire</button> <br>
	</form>

       

templates/bh.html
<!Doctype html>
<html>
<body>
     <p> {{ 2 + 2 }}</p>
</body>
<html>

templates/catalogue.html
<!Doctype html>
<h2> produits disponible</h2>
{% for produit in produits %}
  <div>
     <img src={{{ url_for('static', filename='images/' = produit[3]) }}" width="200">
	   <p>{{ produit[2] }} fcfa </p>
	   <button>commander</button>
  </div>
{% endfor %}

templates/index.html
<!Doctype html>
<html>
  <head>
<meta charset="utf-8">
  </head>
  <body>
<h1>inscription</h1>
<form method="POST" action="/remarque">
  <input type="text" name="nom" placeholder="nom" required> 
  
  <br>
  
  <input type="prenom" name="prenom" placeholder="prnom" required> <br>
  <input type="number" name="numero" placeholder="numero" required> <br>
  <input type="text" name="centre d'interet" placeholder="centre d'interet" required> <br>
</form>
  </body>
</html>

templates/nous.html
<!Doctype html>
<html>
<head>
<meta charset="utf-8">
<style>
  p{color : blue};
</style>
</head>
<body>
   <p>soyez les bienvenus sur vote site prefere, votre site au quotidien</p>
<form action="/rechercher" method="GET">
   <label for="v" >rechercher : </label>
   <input type="text" id= "v" name="v"
   placeholder="rechercher un produit" required>
   <button type="submit">soumettre: </button> <br>
</form>
</body>
</html>

templates/publ.html
<form method="POST" action="{{ url_for('admin_bp.publier') }}">
    {{ prod.csrf_token() }}
	  {{ prod.nom() }}
	  {{ prod.prix() }}
	  {{ prod.image() }}
<input type="text" name="nom" placeholder="nom du produit" required> <br>
<input type="number" name="prix" placeholder="prix" required> <br>
<input type="file" name="image"
	   accept="image/*">
	<button type="submit">ajouter </button>
</form>